### ISSUE TITLE
TF: For the candidate submission form, we need a current salary and expected salary box.   Then on the resume profile page, we need to make the salary display "Total Compensation Range"

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#10]

**Comment by mikedesigner** [comment]
You can add Current Salary / Expect Salary but these will not calculate.  The system cannot calculate salary range, this is out of budget and probably scope of this platform. 

It has to be text input without any "," currently you have already a salary field, "Expected Salary Including Compensation and Bonuses ".

Let me know how you want to proceed with this.

**Comment by alfredchu77** [comment]
We don't need it to calculate. It's more of a data logging so that 1) we collect that information (current AND expected salary) 2) their Total Comp Range will show up on their profile which is based off of the Current Salary package Field that they entered.  This is what we use for the sorting on the filters.

**Comment by mikedesigner** [comment]
Added "Current Salary" to resume submit + back-end + single resume page. 
![screen shot 2016-11-02 at 8 36 41 pm](https://cloud.githubusercontent.com/assets/12680304/19929013/35c0de38-a13c-11e6-800c-855bf19bbf0b.png)

**Comment by alfredchu77** [comment]
Ok but the field should be placed closer together with Expected Salary on the bottom.
