### ISSUE TITLE
TF:  Instead of notes from interviewer. We have a predefined radio button or menu selection for top 3 motivations to move.   I will provide the list of motivations (dropdown/select)

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#11]

**Comment by mikedesigner** [comment]
Please provide me with that list of motivations. Waiting on this to execute.

**Comment by alfredchu77** [comment]
1.        Increase in total compensation
2.       Increase in title
3.       Broader scope of responsibilities
4.       Move to a new location (return to hometown)
5.       Growth oriented company versus more stable flat growth company
6.       Work life balance
7.       Work for a dynamic leader/direct boss
8.       Entrepreneurial culture
9.       Large multi-national company
10.   Private domestic growth company
11.   Pre-IPO company with equity opportunity
12.   Company with a clear top 10 positioning in their industry

**Comment by mikedesigner** [comment]
Ok, can only do "select" this plugin does not support radio buttons or check boxes. So I have added a select with these options in a new question. See attached.

![screen shot 2016-10-31 at 11 00 11 pm](https://cloud.githubusercontent.com/assets/12680304/19858794/ddd9650c-9fbd-11e6-999f-ac0fbc4b6b8c.png)

**Comment by alfredchu77** [comment]
Ok, does this allow them to select the top 3 reasons? We want this info to be published on the candidate profile/resume page.

**Comment by mikedesigner** [comment]
Fixed this. On the front-end resume submit form should look like this. 
![screen shot 2016-11-12 at 3 14 39 pm](https://cloud.githubusercontent.com/assets/12680304/20236516/754f67d2-a8f2-11e6-9914-4b3f9b0e56c0.png)

**Comment by mikedesigner** [comment]
On the back-end you have this, you can multi-select, you need to press ctrl to multiselect.
![screen shot 2016-11-12 at 4 10 36 pm](https://cloud.githubusercontent.com/assets/12680304/20236531/1c5abdba-a8f3-11e6-8f2b-1f5c9b294798.png)
