### ISSUE TITLE
TF: Remove all timestamps for candidates on the list of candidates. This is also for the time stamp that's displayed within their profile.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#12]

**Comment by mikedesigner** [comment]
[ Fixed ], I have removed the time stamps on the resumes list page and candidate resume page. Let me know if I missed anything.

**Comment by alfredchu77** [comment]
Hmm, i'm trying to check the time stamps by going to "Find Candidates".  It takes me to the page but the list of candidates do not show up.  Instead, it just keeps on turning the wait as if it's trying to refresh but something is broken.
