### ISSUE TITLE
TF: Create an alert for job postings so that when a new resume/applicant is uploaded for that job, the client or job poster gets an email notification

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#14]

**Comment by mikedesigner** [comment]
Have you tried this out? Could you create a job then let a candidate apply for it. I was under the impression that this is already working? I could be wrong.

**Comment by alfredchu77** [comment]
I am trying it out but realized that there's no way to login as a candidate because when a candidate submits their resume profile, an account is created but only the email is taken as their username and there's no password - so its impossible to log in again as a candidate

**Comment by mikedesigner** [comment]
Create an alert for job postings so that when a new resume/applicant is uploaded for that job, the client or job poster gets an email notification 

> > > The job poster is an employer not candidate, hence try and post a job and apply to it, see if you ( employer ) get a notification because as the admin I have been getting notifications whenever you upload a new resume.

**Comment by alfredchu77** [comment]
Are we able to make it so that our clients, (employers) can also post "special request" jobs? and then we as the webmaster can upload and apply candidates to those special requests.  Then the clients can either look at the applicants section and receive email notifications?

**Comment by mikedesigner** [comment]
Currently there is only one way for employers to post jobs with the application system. The application system is the one you want to use for posts of "Top 10 xxxxxx" . Its the application system that now if you post a job ( top 10 article ) you can apply to it as candidates. Its the first thing you see on your employer dashboard.

If we make clients fill up a custom form ( which we can, I just need to build a form ) this will be manual, it won't have the application system ( meaning clients wont see an organized list of their jobs and number of candidates who applied for the job ). Also they will not get notifications, they will also not be able mark the position as filled and other functions of the application system. This special request form will have to be a manual procress, they fill in a form, then you will have to contact the client with links to resumes of candidates. They won't have a page which has their special requests in their dashboard.

**Comment by alfredchu77** [comment]
Ok, this is pretty significant, we should discuss how to approach this functionality over the phone.

**Comment by mikedesigner** [comment]
Currently notifications for job posters works. You saw this on your yopmail account. 
![screen shot 2016-11-01 at 12 04 50 pm](https://cloud.githubusercontent.com/assets/12680304/19929102/b8ee5c86-a13c-11e6-9f88-249fa9b1b645.png)
![screen shot 2016-11-01 at 12 04 41 pm](https://cloud.githubusercontent.com/assets/12680304/19929101/b84498fe-a13c-11e6-9be2-b2d958dfb3b4.png)
