### ISSUE TITLE
TF: For the menu after employer login, we don't need submit resume, privacy and terms conditions don't really need links on the top.  We need a Find Candidates and Dashboard link.  The menu is too inconspicuous so need something more obvious and the menu layout should have dashboard and candidates listed up top.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#17]

**Comment by mikedesigner** [comment]
Something was wrong with the menu, WP assigned the footer menu as the top main menu hence you saw the wrong menu. The "Main Menu" needs to be set as the "primary" menu.

![screen shot 2016-10-26 at 8 05 20 pm](https://cloud.githubusercontent.com/assets/12680304/19725411/f43473d2-9bb7-11e6-9f93-70e652ae6ccd.png)

**Comment by mikedesigner** [comment]
The correct, and current menu for employers is like in the image attached. Do let me know if you want to remove the FAQ - Employers, Plans & Pricing ???
![screen shot 2016-10-26 at 8 09 24 pm](https://cloud.githubusercontent.com/assets/12680304/19725500/4e8af040-9bb8-11e6-9de8-de05189b8c97.png)

**Comment by alfredchu77** [comment]
No need for Testimonials.  Instead maybe a Find Candidates would be great.

**Comment by mikedesigner** [comment]
Ok I've added the menu like to the resumes search page. See screen attached. In the future you can change this in the Menu edit: Appearance > Menu  , just be very very careful about the permissions settings for users ( see my attached screen for what I mean ).
![screen shot 2016-10-31 at 10 07 26 pm](https://cloud.githubusercontent.com/assets/12680304/19856949/b6126598-9fb6-11e6-947e-b4e88933f7b3.png)
