### ISSUE TITLE
CGP: 2 issues with the Post a Resume and Sign Up function. 1st issue is the signup email and password process - the password creation is way too stringent and most passwords under 15 letters are very weak, people won't have the patience.  2) once signed up, there is no submit a resume form like we have on TF.  Need to build this section up so that it's logical.  Preferably if the submission is part of the sign up like TF.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#18]

**Comment by mikedesigner** [comment]
1) This is Wordpress native, these days WP is under constant attack and will by default not accept weak passwords, even big sites like Godaddy and others are doing this. Its for your site security. If you sign up for Wordpress you will be given a strong password by default.

2) Once signed up, there is no submit a resume form like we have on TF.

> I will remove the employer sign-up, thats not in the project scope not sure why I left it there.
> I assume you sign-up using the top menu ( because you didnt fully describe your steps so I am just assuming since you can also sign up if you submit your resume ). But it wasn't our intention to build a dashboard area for candidates because we wanted them to find jobs by using the "Find Job" page and explore your website. However I believe we can change this and have them land on a page http://cgp.kotebo.com/myaccount/manage-resumes/  ( Candidate Dashboard / My Resumes ) but we need to decide what information goes here. Thought I reckon it would make more sence if they land on the Find-A-Job page which lists your industries and jobs under each.

Need to build this section up so that it's logical. Preferably if the submission is part of the sign up like TF.

> This is not possible and it wasn't our initial intention to build it with this logic since CGP and TF use different themes integrated with WP Job Manager differently. Lets do this in the next phase / build as it will require some more custom work to get it working properly as you need.

**Comment by alfredchu77** [comment]
I don't think you understand and have looked into CGP "Submit a resume".  The CGP site loses its purpose if candidates cannot submit their resume for a particular job. It should be included in the WP Job manager plugin. We don't need to create a dashboard for candidates but once they see a job, they should be able to apply for that job by send in their resume or some type of profile info.  When I click on submit a resume link under the candidates menu.  I only get to a login page. Why do we call that link "submit your resume" if the candidate cannot submit their resume?  This should not be a custom function.

**Comment by alfredchu77** [comment]
please take a look at the screenshots i sent to you on wechat.  When you click submit resume, you can login, then there's buttons that ask you to submit but the user is not able to do anything except to click next. Suggest that you try it out to see what i mean.

**Comment by mikedesigner** [comment]
I see, the submit resume form is broken, not sure why but its probably some of my functional php code edits. I will look into fixing this tomorrow.

**Comment by mikedesigner** [comment]
![screen shot 2016-11-03 at 11 15 18 am](https://cloud.githubusercontent.com/assets/12680304/19955190/d805a534-a1b9-11e6-9b0e-92658c482b55.png)

**Comment by alfredchu77** [comment]
The resume content box does not work.  I think we need to make this optional but CV attachment required.  Also, what is the difference between region and location? Seems like we're using Region more than location.
