### ISSUE TITLE
TF: and Maybe on CGP.  The Forgot your password and password reset function takes me to a Word Press page.  I also receive an email saying my username is webmaster.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#19]

**Comment by mikedesigner** [comment]
Added part of the fix. Only administrators + editors can access /wp-admin other users will get redirected to homepage (if logged out) / or dashboard (if logged in).

**Comment by mikedesigner** [comment]
I am assuming you mean you see this page when you reset your password ( see attached screen below ).
![screen shot 2016-10-31 at 5 55 42 pm](https://cloud.githubusercontent.com/assets/12680304/19850448/85fafa78-9f93-11e6-86b1-bdadaec372ea.png)

**Comment by mikedesigner** [comment]
[ FIXED ]  Please test and if happy close this.

I've overridden the default wordpress login page (see attached screen). I've also made it redirect to the homepage ( new login page ) after the user submits a new password.

Take it for a spin.
![screen shot 2016-10-31 at 9 41 11 pm](https://cloud.githubusercontent.com/assets/12680304/19856112/0f5ce226-9fb3-11e6-8388-b3147dc9b200.png)

**Comment by alfredchu77** [comment]
Will close this soon but I want to make note that the Password Reset email i receive says that my Username: webmaster.  I think we need to rewrite this entire email to make a little more sense.
