### ISSUE TITLE
TF: Candidates Cannot Login 

### ISSUE THREAD

**Issue by mikedesigner** [mikedesigner/CGP#21]
I am trying it out but realized that there's no way to login as a candidate because when a candidate submits their resume profile, an account is created but only the email is taken as their username and there's no password - so its impossible to log in again as a candidate

>>> I need to see if its possible, maybe you can create this. The only way candidates can choose a password now is if they create an account through registration ( which we have disabled registration for candidates since you told me you will be the candidates since you do not want your clients / employers to directly interact with candidates. The solution here is for me to create another form for the candidates to register that you ( webmaster / editor ) will have to then create the candidate account.

**Comment by alfredchu77** [comment]
We need to remove the Sign In link and maybe the whole first row because candidates don't really need to sign-in.

**Comment by mikedesigner** [comment]
Removing the sign in link means the header will look boring and looses its function. I've added two links ( Register / Submit Resume ) to keep things functional.  See attached image.

![screen shot 2016-11-12 at 4 07 46 pm](https://cloud.githubusercontent.com/assets/12680304/20236510/40d714f0-a8f2-11e6-9169-e506daa98929.png)
