### ISSUE TITLE
TF: Went thru the menu and fixed a bunch of broken links.  Need to create a How It Works page - copy from Hired.com.  Also need to create About page.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#25]

**Comment by alfredchu77** [comment]
We can use this as closure text for our How It Works Page for Employers and for Candidates. 

Why Companies Use Top20talent?
We pick up where all other online platforms stop.  Retained quality passive candidates at RPO pricing.  Companies want the best Quality talent, Quickly and at the lowest Cost possible.  Traditional online platforms only access “active” candidates which represents less than 20% of the available talent.  Passive talent needs to be sourced offline and needs expert recruiters to identify and qualify top 20% talent relative to their industry, function and location.  Our platform provides companies access to the top 20% talent from all possible candidates, active and passive. 

Why Candidates are enabled by Top20talent?
We provide Top20talent the opportunity to confidentially explore their value on the market with exclusive access to top quality opportunities that match their background and most importantly their top motivators for making a career decision.  With industry expert advice and specific preparation for interviews, our candidates are given the opportunity to present themselves in a way that will maximize their value when they decide to make a change.

**Comment by mikedesigner** [comment]
I've done something better. Something like this that you can go and edit:

For Candidates:
http://tf.kotebo.com/how-it-works-candidates/

For Employers:
http://tf.kotebo.com/how-it-works-employers/
