### ISSUE TITLE
Testimonials.  No need for separate link but maybe it can be a jump to the section link.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#3]

**Comment by mikedesigner** [comment]
So you need this menu to be there but if a user clicks on it, it goes to the Homepage and scrolls down to "Testimonials" section. You also need me to delete or disable the testimonials page ( probably put it in draft or private page mode incase you want to use it in the future ).

Correct my understanding.

**Comment by alfredchu77** [comment]
yes, it should only be a section that scrolls down.  The page should be put in draft for the future but dont think we'll use it much.
