### ISSUE TITLE
TF: Need an About Page.  Content is below.  

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#31]
The Top20Talent Story
Since 1998 our founders have been successfully operating in the global recruitment industry and observing and testing how technology and the internet could disrupt the recruitment industry.  An industry that has largely remained unchanged for the last 30 years.  There have been many predictions of the demise of the offline recruitment business model but as we enter 2017 the industry continues to grow every year because these online platforms have failed to solve the problem of identifying and attracting top 20% mid to senior level passive talent efficiently and at a reasonable cost.  Our passion to solve this problem and almost 20 years of planning and 2-3 years testing we created the solution virtually every company needs.  They need the Top 20% talent, as fast as possible and a pricing structure that is significantly lower than traditional offline specialist recruiters.  Essentially they want retained quality candidates, immediately with RPO pricing.  Candidates want a confidential process whereby they can evalutate top of market opportunities without having to send their resumes job postings on the hundreds of websites or to many different offline recruiters that have limited access to opportunities.  We welcome you to Top20Talent which is the first O2O platform of its kind that links the top 20% of the talent in the market with the top companies.

**Comment by mikedesigner** [comment]
This is way too much text ( not your problem I am sure but your partners ), so I have broken down your content into chunks. No body is going to read that much. Here is the page, feel free to edit the page. 
/about/

![screen shot 2016-11-16 at 19 27 36](https://cloud.githubusercontent.com/assets/12680304/20345931/57ec7bf4-ac34-11e6-8fa3-8268a2520e28.png)
