### ISSUE TITLE
TF: Disable Email Notifications to Candidates - Contact Button Emails the Webmaster/Site Admin

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#34]

**Comment by mikedesigner** [comment]
I have removed the email contact method from the Applications back-end of employers.
![screen shot 2016-11-17 at 11 52 24 pm](https://cloud.githubusercontent.com/assets/12680304/20397042/2ca1e304-ad23-11e6-893d-23bde6d1bdea.png)
