### ISSUE TITLE
TF: for Editors/Webmaster, allow to apply to job/Job Listings - Post a Job (Request a Candidate on the front).  

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#36]

**Comment by mikedesigner** [comment]
Added button for "Apply to Job" for admins / editors / sub-editors , next to View Job Applications.
![screen shot 2016-11-16 at 5 23 12 pm](https://cloud.githubusercontent.com/assets/12680304/20341517/8648371c-ac21-11e6-9135-e703602b6787.png)
