### ISSUE TITLE
TF: Submit Resume Form, Client Registration, and Resume Profile Display forms need to be adjusted to Black and White text and also more compact spacing/compact form boxes.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#38]

**Comment by mikedesigner** [comment]
Made modifications to the register form + submit resume + single resume page: eg: http://tf.kotebo.com/resume/tom-4a3y8msp-store-manager-shanghai/  

Made labels bolder and used darker colors as well as tighter spacing / smaller headers.
