### ISSUE TITLE
TF: Salary Ranges Update with USD Equivalent

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#39]

**Comment by alfredchu77** [comment]
Please redo the salary ranges with USD labeling.  We will convert by hand when we upload to make sure they are in the right RMB range.. Also added two more ranges at the bottom.

Below 400k ($60k)
400k-600 ($60k-$90k)
600-800 ($90k-$120k)
800-1M ($120k-$145k)
1-1.3M ($145k-$190k)
1.3-1.6M ($190k-$235k)
1.6-1.9M ($235k-$280k)
1.9-2.2M ($280k-$320k)
2.2M-2.5M ($320k-$365k)
2.5M+ ($365k+)

**Comment by mikedesigner** [comment]
Done for the filter. Y
![screen shot 2016-11-17 at 11 35 07 pm](https://cloud.githubusercontent.com/assets/12680304/20395790/0c8f98bc-ad1f-11e6-9ec5-e1e83bd8c0c1.png)
ou need to update the Resumes > Salaries ( tags ) in the back-end for the articles.
