### ISSUE TITLE
Remove Companies page under Candidates menu. We don't need to display a list of companies.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#4]

**Comment by mikedesigner** [comment]
Ok, menu removed. under Apperances > Menu   , close this ticket if satisfied. 

![screen shot 2016-10-26 at 8 23 19 pm](https://cloud.githubusercontent.com/assets/12680304/19725790/2ed61d54-9bba-11e6-82dc-b3594f5f18fe.png)
