### ISSUE TITLE
Submit Your Resume under the Candidate menu requires a login.  Is there a way we can have them submit without logging in? Please change this.

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#5]

**Comment by mikedesigner** [comment]
The reason why you need to login is in order to get notified if your contacted as a candidate, also to be able to bookmark jobs, it also protects you from spam and keeps your db clean with less duplicate candidates.

**Comment by alfredchu77** [comment]
ok, can we make it like TF where the form will create an account?

**Comment by mikedesigner** [comment]
I'm afraid this is not possible and out of the project scope for now, lets move this to Phase 2.  Candidates will be able to register on CGP. Those who submit applications or submit resumes are automatically registered so you can contact them later and they can post more resumes and edit information.
