### ISSUE TITLE
Move Join Us under the information menu and set as its own Menu Link.  This is an important link and we need this as its separate link by itself on the menu bar

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#6]

**Comment by mikedesigner** [comment]
You mean you want to add the Join Us right after the information link like this? 
![screen shot 2016-11-03 at 10 40 56 am](https://cloud.githubusercontent.com/assets/12680304/19954352/84eeec18-a1b2-11e6-9d63-c23695f66c08.png)

**Comment by mikedesigner** [comment]
I've shown you how to do this.
