### ISSUE TITLE
TF: For Cities or regions on the candidate search and on the resume submission form, put in Shanghai, Beijing, Guangzhou, Suzhou, Hong Kong, Singapore

### ISSUE THREAD

**Issue by alfredchu77** [mikedesigner/CGP#7]

**Comment by mikedesigner** [comment]
You can do this under the Resumes > Regions / Job Posts Regions. See my attached images, try this. 

![screen shot 2016-10-26 at 8 14 14 pm](https://cloud.githubusercontent.com/assets/12680304/19725687/8e4d6900-9bb9-11e6-991f-ff09b67c3ec2.png)
![screen shot 2016-10-26 at 8 15 05 pm](https://cloud.githubusercontent.com/assets/12680304/19725688/8e8ae96a-9bb9-11e6-88cb-9b86fe949591.png)

**Comment by alfredchu77** [comment]
Went through and added but 1) the menu under job search didn't add the additional cities I added.  Also didn't see any changes under Resumes when i added the additional cities in Resume Regions

**Comment by mikedesigner** [comment]
Can you try this again? I think at that time we were also updating this function. For resumes I've tested it, also for Job listings, its under regions when you try to Post A Job.

**Comment by alfredchu77** [comment]
When I go to Find Candidates, the Cities Menu is still the old list of cities with Singapore spelled incorrectly as Singpore.  I then tried to log in as webmaster to try to change the cities again, I can't get into the WP dashboard.  Instead i get an error message: "The page isn’t redirecting properly"
